server:
  port: 7001
spring:
  application:
    name: microservice-config-eureka-server-7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。单机版
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  server:
#    peer-eureka-nodes-update-interval-ms: 30000
#    renewal-threshold-update-interval-ms: 15000