server:
  port: 7003
spring:
  application:
    name: microservice-config-eureka-server-7003
eureka:
  instance:
    hostname: eureka7003.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  server:
#    peer-eureka-nodes-update-interval-ms: 30000
#    renewal-threshold-update-interval-ms: 15000