server:
  port: 8002
spring:
  application:
    name: microservicecloud-config-provider-cilent-dept
  datasource:
    url: jdbc:mysql://47.107.172.70:3306/cloudDB02

eureka:
  client:
    instance:
      instance-id: provider-8002.com
info:
  app.name: microservice-config-provider-client8002