#  本地映射 config-1000.com config server
server:
  port: 1000
spring:
  application:
    name: microservice-configcenter # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangyun-zero/microservicecloud-config.git  # config 读取配置文件所在 git 仓库
        # 安全验证下还需要 git 的用户密码
#        username:
#        password: